# Generated by Django 4.2.7 on 2023-12-01 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("ads_count", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Ads",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="ads_images")),
                ("price", models.IntegerField(default=0)),
                ("content", models.TextField()),
                ("is_top", models.BooleanField(default=False)),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "sub_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_category",
                        to="olx.category",
                    ),
                ),
            ],
        ),
    ]
