# Generated by Django 4.2.7 on 2023-12-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("olx", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="title",
            field=models.CharField(help_text="This is the help text", max_length=255),
        ),
    ]
