# Generated by Django 4.2.7 on 2023-12-01 13:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("olx", "0002_alter_category_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ads",
            name="image",
        ),
    ]
