# Generated by Django 5.0 on 2023-12-18 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olx', '0003_remove_ads_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ads',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
